# 消除异步传染性

## 解决的问题

+ code

  ```js
  async function getUser() {
    return await fetch("./1.json");
  }

  async function m1() {
    const res = await getUser();
    return res
  }

  async function m2() {
    const res = await m1();
    return res
  }

  async function m3() {
    const res = await m2();
    return res
  }

  async function main() {
    const res = await m3();
    console.log(user)
  }
  ```

## 解决

+ code

  ```js
  function run(func) {
    // 1. 改动fetch
    const lodFetch = window.fetch;
    const cache = {
      status: 'pending',
      value: null
    };
    function newFetch(...args) {
      // 是否存在缓存
      if(cache.status === "fulfilled") {
        // 成功
        return cache.value;
      }else if(cache.status === "rejected") {
        // 失败
        throw new cache.value;
      }

      // 不存在缓存
      const p = lodFetch(...args).then(res => res.json()).then((data) => {
        cache.status = "fulfilled";
        cache.value = data;
      }).catch(err => {
        cache.value = err;
        cache.status = "rejected";
      });

      // 抛出错误
      throw p

    }

    window.fetch = newFetch;

    // 2. 执行 func
    try {
      func();
    } catch (error) {
      // 等待请求完成后，重新请求

      if(error instanceof Promise) {
        error.finally(() => {
          window.fetch = newFetch;
          func();
          window.fetch = lodFetch;
        })
      }
    }

    // 3. 改回fetch
    window.fetch = lodFetch;
  }
  ```

  ```js
  function getUser() {
    return fetch("./1.json");
  }

  function m1() {
    const res =  getUser();
    return res
  }

  function m2() {
    const res =  m1();
    return res
  }

  function m3() {
    const res =  m2();
    return res
  }

  function main() {
    const res =  m3();
    console.log(res)
  }

  run(main)
  ```
